### ISSUE TITLE
Generating a dungeon produce "boolean index" errors

### ISSUE THREAD

**Issue by el0hh** [orphu/mcdungeon#402]
mcdungeon-v0.17.1/dungeon.py:2190: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 2; dimension is 256 but corresponding boolean dimension is 72
  chunk.Blocks[air] = materials._floor.val
/home/eike/minecraft_server/mcdungeon-v0.17.1/dungeon.py:2190: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 2; dimension is 256 but corresponding boolean dimension is 75
  chunk.Blocks[air] = materials._floor.val

mc 1.11.2
mcd 0.17.1

hard_mode with less silverfish and:
Elytra:50,1,0
Shulker Shell:40,1-2,0
Totem of Undying:50,1,0

If I enter the dungeon mc show a lot of errors like this:

[10:24:04] [Server thread/ERROR]: Failed to load data for block entity mob_spawner
java.lang.NullPointerException
        at aji.a(SourceFile:162) ~[minecraft_server.jar:?]
        at asr.a(SourceFile:78) ~[minecraft_server.jar:?]
        at asc.a(SourceFile:120) [minecraft_server.jar:?]
        at avd.a(SourceFile:343) [minecraft_server.jar:?]
        at avd.a(SourceFile:97) [minecraft_server.jar:?]
        at avd.a(SourceFile:72) [minecraft_server.jar:?]
        at lv.f(SourceFile:124) [minecraft_server.jar:?]
        at lv.b(SourceFile:81) [minecraft_server.jar:?]
        at mb.<init>(SourceFile:40) [minecraft_server.jar:?]
        at mc.c(SourceFile:196) [minecraft_server.jar:?]
        at mc.c(SourceFile:288) [minecraft_server.jar:?]
        at mt.d(SourceFile:325) [minecraft_server.jar:?]
        at mi.a(SourceFile:513) [minecraft_server.jar:?]
        at iz.a(SourceFile:126) [minecraft_server.jar:?]
        at iz$a.a(SourceFile:57) [minecraft_server.jar:?]
        at fo$1.run(SourceFile:13) [minecraft_server.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at h.a(SourceFile:46) [minecraft_server.jar:?]
        at net.minecraft.server.MinecraftServer.D(SourceFile:606) [minecraft_server.jar:?]
        at lh.D(SourceFile:335) [minecraft_server.jar:?]
        at net.minecraft.server.MinecraftServer.C(SourceFile:562) [minecraft_server.jar:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:466) [minecraft_server.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

Not sure if this apply to the first errors.

**Comment by JiFish** [comment]
What version of MCDungeon are you running? Which platform are you running it on? (Python, Windows?) Which version of minecraft are you running? Are you running any mods? Please provide as much detail as you can.

**Comment by el0hh** [comment]
Hi, I did!

mc 1.11.2 vanilla
mcd 0.17.1

ubuntu 16.04
Python 2.7.12
Python 3.5.2 ist installed, but python2 ist default.

**Comment by JiFish** [comment]
The problems may be unrelated. It's hard to tell.

The first issue looks like a problem with NumPy. Which version of NumPy are you using?

**Comment by el0hh** [comment]
python-numpy                                1:1.11.0-1ubuntu1

**Comment by JiFish** [comment]
@orphu: What version of NumPy did you compile against? I must admit, I haven't updated my local version for a while.

**Comment by orphu** [comment]
pip show numpy

Name: numpy
Version: 1.11.0

I list 1.11.0 as a req in the docs:

http://mcdungeon.readthedocs.io/en/latest/downloading-running/#requirements

This does look like a numpy warning though. From what I can tell, it's just a warning and maybe even a numpy bug. 

Do you have any verbose warnings turned on, or are you running the latest ubuntu package for numpy? Does this occur with MCD 0.17.0? 

I don't think the java errors are related.

**Comment by JiFish** [comment]
Agreed, the java errors look like some sort of problem with a spawners NBT tags. (Maybe again due to entity id changes, though I thought I caught them all.) But without knowing which spawner it could be a pain to track down. It may require repeatedly generating dungeons with different spawners and testing for this error.

@el0hh Did you notice any specific spawners being non-functional? Do the dungeons otherwise seem to operate correctly?

**Comment by el0hh** [comment]
@orphu No verbose warning where turned on, my system get requlary updated, yes it's the latest version of numpy.

@JiFish Yes the Dungeon looks good, can't tell if a spawner is non functional.

**Comment by orphu** [comment]
Hm, not sure. From what I can tell, that error may have been an old numpy bug that was fixed prior to 1.11.0. I'm not able to repro with numpy versions 1.11.x or 1.12.0, but I'm installing from pip. I typically install python with pyenv to avoid messing with the system python. 

Can you verify what version of numpy you're actually using? (vs what is installed)

From your MCDungeon directory, try this:

/usr/bin/env python -c 'import numpy; print numpy.version.version'

**Comment by el0hh** [comment]
mcdungeon-v0.17.1$ /usr/bin/env python -c 'import numpy; print numpy.version.version'
1.11.0

on a patched Ubuntu 16.04.2 LTS

**Comment by JiFish** [comment]
I have spun the entity spawner issuer in to it's own issue #403 But without discovering which spawner is broken, it could be a while before this is fixed.

**Comment by orphu** [comment]
@el0hh 

I've managed to reproduce this in a Ubuntu 16.04.2 install. Best I can tell, it's an old bug in numpy, and for some reason their package is affected (even though it seems to have been fixed a long time ago in upstream nympy)

It should be harmless (it's just a warning). If it bothers you, I'd suggest installing python and dependencies via [pyenv](https://github.com/yyuu/pyenv).

**Comment by el0hh** [comment]
Thank you!



Am 20.02.2017 um 03:06 schrieb Tyler Lund:
