### ISSUE TITLE
[Server thread/ERROR]: Failed to load data for block entity mob_spawner

### ISSUE THREAD

**Issue by JiFish** [orphu/mcdungeon#403]
Server errors when playing a map with a dungeon on. This probably indicates some bad spawner NBT tags somewhere.

```
[10:24:04] [Server thread/ERROR]: Failed to load data for block entity mob_spawner
java.lang.NullPointerException
at aji.a(SourceFile:162) ~[minecraft_server.jar:?]
at asr.a(SourceFile:78) ~[minecraft_server.jar:?]
at asc.a(SourceFile:120) [minecraft_server.jar:?]
at avd.a(SourceFile:343) [minecraft_server.jar:?]
at avd.a(SourceFile:97) [minecraft_server.jar:?]
at avd.a(SourceFile:72) [minecraft_server.jar:?]
at lv.f(SourceFile:124) [minecraft_server.jar:?]
at lv.b(SourceFile:81) [minecraft_server.jar:?]
at mb.(SourceFile:40) [minecraft_server.jar:?]
at mc.c(SourceFile:196) [minecraft_server.jar:?]
at mc.c(SourceFile:288) [minecraft_server.jar:?]
at mt.d(SourceFile:325) [minecraft_server.jar:?]
at mi.a(SourceFile:513) [minecraft_server.jar:?]
at iz.a(SourceFile:126) [minecraft_server.jar:?]
at iz$a.a(SourceFile:57) [minecraft_server.jar:?]
at fo$1.run(SourceFile:13) [minecraft_server.jar:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
at h.a(SourceFile:46) [minecraft_server.jar:?]
at net.minecraft.server.MinecraftServer.D(SourceFile:606) [minecraft_server.jar:?]
at lh.D(SourceFile:335) [minecraft_server.jar:?]
at net.minecraft.server.MinecraftServer.C(SourceFile:562) [minecraft_server.jar:?]
at net.minecraft.server.MinecraftServer.run(SourceFile:466) [minecraft_server.jar:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by orphu** [comment]
Still seeing these. I have an example map now, so maybe I can track it down. 

`22:54:00	ase	Server thread	error	Failed to load data for block entity minecraft:mob_spawner
`

**Comment by orphu** [comment]
I've narrowed this down to the "Catling" custom spawner. There may be more, but this one definitely causes the error and produces empty spawners. 

I've not figured out what's wrong with it yet (it's kind of big and gnarly)

**Comment by JiFish** [comment]
Dang it. It was hard enough getting that one working in the first place! I should have guessed it would be this one that broke.

OK, I best pick this one up. I'll try to find time to look at it this evening or tomorrow.

**Comment by JiFish** [comment]
@orphu: This is 100% a change to minecraft tags. In my test world, I was able to generate those spawners fine, but in brand new map they broke as described. I think this means in addition to my fixing this spawner, we'll need to update the dataversion?

I've got to remember to always generate a new test map with new versions.

**Comment by orphu** [comment]
Hm. I updated the DV to the 1.11.2 version in 8f01a20. Could look at updating it the the latest 1.12 snapshot version and see what happens.

**Comment by JiFish** [comment]
It looks like it's spawners that use SpawnPotentials that are broken.

**Comment by JiFish** [comment]
Think I've got it. Looks like SpawnData is now required. The actual contents doesn't matter so much. If you set the Delay to -1 it gets overwritten before anything the first spawn anyway.

**Comment by orphu** [comment]
Could just have the util function fill in a dummy SpawnData default tag. YAML files could override it if they need to. 

This seems unrelated to the original report now. But maybe with all the changes that's been fixed too.

**Comment by JiFish** [comment]
> Could just have the util function fill in a dummy SpawnData default tag. YAML files could override it if they need to.

Good idea, I tried that and it seemed to work perfectly.

> This seems unrelated to the original report now. But maybe with all the changes that's been fixed too.

I'm not so sure. Maybe SpawnData tags have been required since 1.11? Anyway, needs retesting.

**Comment by JiFish** [comment]
I'm not getting this error in the snapshot server with the latest version of MCDungeon. I think this is fixed.
